# Site settings
title:필립|온라인 공식 바이럴 광고대행사
email:ndk0929@gmail.com
description:온라인 공식|바이럴 광고 대행사 필립 광고운영대행 디자인 광고진단 마케팅 교육까지> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://philip.kr" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
